### ISSUE TITLE
Function float_from_bitstring doesn't work for some inputs

### ISSUE THREAD

**Issue by w0nsh** [nerkulec/ANM#1]
Input: 0000000101110000000000000000000000000000000000000000000000000000

Exception:
`LoadError: DomainError with -1000:
Cannot raise an integer x to a negative power -1000.`

Fix:
Change `return sign*m*2^c` to `return sign*m*2.0^c`.

**Comment by nerkulec** [comment]
Fixed in commit `88347aa7df39d6313d032f642b3bc20efbfdc7dc`
